config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    post 'users/sign_up' => 'devise/registrations#create'
  end

  resources :groups, only: [:splash, :index, :show, :create, :new, :edit, :update, :destroy] do
    resources :entities
  end

  get '/splash' => 'groups#splash'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "groups#splash"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  validates :name, presence: true
  validates :user_id, :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }

  belongs_to :user
  has_many :groups, dependent: :destroy
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, :icon, presence: true

  belongs_to :user
  has_many :entities, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # after_initialize :init
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :groups, counter_cache: true
  has_many :entities

  # private

  # def init
  #   self.groups_count ||= 0
  #   true
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :html, :json
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def after_sign_in_path_for(_resource)
    groups_path
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[show edit update destroy]

  # GET /entities or /entities.json
  def index
    @entities = Entity.all
  end

  # GET /entities/1 or /entities/1.json
  def show; end

  # GET /entities/new
  def new
    @group = Group.find(params[:group_id])
    @entity = Entity.new
  end

  # GET /entities/1/edit
  def edit; end

  # POST /entities or /entities.json
  def create
    @entity = current_user.entities.new(entity_params)
    @group = Group.find(params[:group_id])

    respond_to do |format|
      if @entity.save
        format.html { redirect_to group_url(@group), notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1 or /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to entity_url(@entity), notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1 or /entities/1.json
  def destroy
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @entity = Entity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit(:name, :amount, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:splash]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
    @group = Group.find(params[:id])
    @entities = @group.entities.order(created_at: :desc)
    @total = @group.entities.sum(&:amount)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @user = current_user
    @group = @user.groups.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def splash; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
    @entities = @group.entities
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :user_id, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/entities/_entity.html.erb
<div id="<%= dom_id entity %>">
  <p>
    <strong>Name:</strong>
    <%= entity.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= entity.amount %>
  </p>

</div>

app/views/entities/_form.html.erb
<div class="devise-page">
  <%= form_with model: [@group, @group.entities.build], local: true do |form| %>
    <div class="top">
      <a href="<%= group_path(@group) %>"> <i class="fa fa-arrow-left" aria-hidden="true"></i> </a>
      <h2>NEW TRANSACTION</h2>
      <div class="actions">
        <%= form.submit "Create", class: 'toplink' %>
      </div>
    </div>
    <% if entity.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

        <ul>
          <% entity.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="rest">
      <div class="field">
        <%= form.text_field :name, placeholder: 'Transaction Name', required: true %>
      </div>

      <div class="field" >
        <%= form.number_field :amount, placeholder: 'Transaction Cost', required: true %>
      </div>

      <div class="field">
        <%= form.select :group_id, current_user.groups.collect {|group| [group.name, group.id]},{ include_blank: true}, class:"custom-select", id:"inputGroupSelect01", placeholder: 'Transaction Category', required: true %><br>
      </div>
    </div>
  <% end %>
</div>

app/views/entities/edit.html.erb
<h1>Editing entity</h1>

<%= render "form", entity: @entity %>

<br>

<div>
  <%= link_to "Show this entity", @entity %> |
  <%= link_to "Back to entities", entities_path %>
</div>

app/views/entities/index.html.erb
<h1>Transactions</h1>

<div id="entities">
  <% @entities.each do |entity| %>
    <%= render entity %>
    <p>
      <%= link_to "Show this entity", entity %>
    </p>
  <% end %>
</div>

<%= link_to "New entity", new_entity_path %>

app/views/entities/new.html.erb
<%= render "form", entity: @entity %>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.text_field :icon %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class="group">
  <div class="icon">
    <%= image_tag group.icon, size: "60x60", alt: "icon" if group.icon %>
  </div>
  <div class="name">
    <strong><%= group.name %></strong>
    <small><%= group.created_at.strftime("%d-%b-%Y")  %></small>
  </div>
  <strong>$<%= group.entities.sum(&:amount) %></strong>

</div>

app/views/groups/edit.html.erb
<div class="devise-page">
  <%= form_with(model: @group, local: true) do |form| %>
    <div class="top">
      <a href="<%= group_path %>"> <i class="fa fa-arrow-left" aria-hidden="true"></i> </a>
      <h2>EDIT CATEGORY</h2>
      <div class="actions">
        <%= form.submit "Update", class: 'toplink' %>
      </div>
    </div>
    <% if @group.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

        <ul>
          <% @group.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="rest pad">
      <div class="field">
        <%= form.text_field :name, placeholder: 'Name of Category', required: true %>
      </div>

      <div class="field">
        <%= form.text_field :icon, placeholder: 'link to image address', required: true %>
      </div>

      <div class="field">
        <%= form.text_field :description, placeholder: 'category description goes here.' %>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/groups/index.html.erb
<div class="devise-page block">
  <div class="top">
    <a href="users/edit"  title="edit profile"> <i class="fa fa-bars" aria-hidden="true"></i> </a>
    <h2>CATEGORIES</h2>
    <div class="actions">
      <a href="/users/sign_out" data-method="delete" data-confirm="Are you sure?" title="sign out"> <i class="fa fa-power-off" aria-hidden="true"></i> </a>
    </div>
  </div>
  <div>
    <div id="groups">
      <% @groups.each do |group| %>
        <% if group.user_id === current_user.id %>
          <%= link_to group do %>
            <%= render group %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="btn-div">
    <%= link_to "NEW CATEGORY", new_group_path, class: 'new-cat' %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="devise-page">
  <%= form_with(model: @group, local: true) do |form| %>
    <div class="top">
      <a href="/groups"> <i class="fa fa-arrow-left" aria-hidden="true"></i> </a>
      <h2>NEW CATEGORY</h2>
      <div class="actions">
        <%= form.submit "Create", class: 'toplink' %>
      </div>
    </div>
    <% if @group.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

        <ul>
          <% @group.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="rest pad">
      <div class="field">
        <%= form.text_field :name, placeholder: 'Name of Category', required: true %>
      </div>

      <div class="field">
        <%= form.text_field :icon, placeholder: 'link to image address', required: true %>
      </div>

      <div class="field">
        <%= form.text_field :description, placeholder: 'category description goes here.' %>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class="details-page">
  <div class="top">
    <a href="/groups"> <i class="fa fa-arrow-left" aria-hidden="true"></i> </a>
    <h2>TRANSACTIONS</h2>
    <div class="actions">
      <%= link_to "Edit", edit_group_path(@group), class: 'toplink' %>
    </div>
  </div>
  <div class="down">
    <div class="group-info">
      <%= image_tag @group.icon, size: "60x60", alt: "icon" %>
      <h2><%= @group.name.upcase %></h2>
      <strong>Total Amount: $<%= @total %></strong>
    </div>
    <div class="description">
      <p><%= @group.description %></p>
      <%= button_to "Delete Category", @group, method: :delete, class: 'delete' %>
    </div>
    <div class="transactions">
      <% @entities.each do |entity| %>
        <div class="whole">
        <div class="trans">
          <strong><%= entity.name.upcase %></strong>
          <small><%= entity.created_at.strftime("%d-%b-%Y")  %> at <%= entity.created_at.strftime("%l:%M %P") %></small>
        </div>
        <h4>Amount: $<%= entity.amount %><h4>
        </div>
        <hr>
      <% end %>
    </div>
</div>
<div class="btn-div">
  <%= link_to "NEW TRANSACTION", new_group_entity_path(@group.id), class: 'new-cat' %>
</div>
<div>
</div>

app/views/groups/splash.html.erb
<div class="splash">
  <div class="logo">
    <h1>Budget_R</h1>
    <small>Manage your budget and transactions betteR</small>
  </div>
  <div class="auths">
    <%= link_to "Log in", new_user_session_path, :class => 'login' %><br />
    <%= link_to "Sign up", new_user_registration_path, :class => 'signup' %><br />
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetR</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://kit.fontawesome.com/30c417e8c0.js" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>